name: First Workflow
on: [push]

jobs:
   testing-wf-commands:
      runs-on: ubuntu-latest
      steps:
        - name: Setting an error message
          run: echo "::error::Missing semicolon"
        - name: Setting an error message witj params
          run: echo"::error title:error title,file=app.js,line=2,endLine=3,col=5,endColum=7::Missing Semicolon"
   display-wd-info-windows:
      runs-on: windows-latest
      steps:
        - name: Display working Directory & List Files
          run: |
            Get-Location
            dir
            echo $env:GITHUB_SHA
            echo $env:GITHUB_REPOSITORY
            echo $env:GITHUB_WORKSPACE
        - name: Python Shell
          shell: python
          run: |
             import platform
             print(platform)